// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkireodvrghbejjoeonj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1raXJlb2R2cmdoYmVqam9lb25qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxOTM1MjUsImV4cCI6MjA2ODc2OTUyNX0.6r7IE99w-AIZ_1tbh5vJR5I2dcwh8vryetfskNFHeng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});